### ISSUE TITLE
ARVR option does not seem to work anymore

### ISSUE THREAD

**Issue by Pewsplosions** [BastiaanOlij/gdleapmotion#8] opened 2018-08-06 21:09 UTC
I am trying to use the Leap Motion addon in conjunction with the Open VR addon.

Any time I select the Arvr checkbox in the Script Variables section and try to play my scene the loader gets stuck on "Construct gdnative interface" and never starts.

I looked at the code and tried to compile it myself. I have never tried to do any GDNative things of any kind and am not the biggest expert in C++ in general but I looked at the code some.

It seems as though the ARVRServer may have changed since this plugin was written. In gdlm_sensor.cpp line 608-609 there is reference to ARVRServer::get_hmd_transform() and ARVRServer::get_last_process_usec() and ARVRServer::get_last_frame_usec();

None of these methods seem to be part of ARVRServer anymore. So do I just have a newer version of the ARVR code that this Leap addon is not compatible with?

Thanks for any help provided. I may eventually try to actually figure it out, but have some deadlines on other projects now so guessing this will not make it into my schedule very soon.

**Comment by BastiaanOlij** [comment] 2018-08-06 21:40
Hi @Pewsplosions,

What version of Godot are you using? Most of these changes are all added in Godot 3.0.5 so if you are using an earlier Godot 3.0 build they won't be there.

Also keep in mind that for the OpenVR plugin the master branch can only be used with Godot 3.1, while the plugin in the asset store only works with Godot 3.0

**Comment by Pewsplosions** [comment] 2018-08-06 22:00
I am using v3.0.6.stable.official.8314054 through steam. I installed the addons for OpenVR and Leap through the asset tab in the editor. 

The OpenVR seems to work well. When I add the Leap to the ARVROrigin, I can then play the scene and the hands seem to kind of work but are just sitting at the center on the floor. Then I stop and check the Arvr option, assuming that is what puts the hands in the correct orientation to the HMD. But when I try to play the scene I just get what I mentioned above.

I could be missing something as far as the code things go though. All I did was compare the errors I got from the compiler after I pulled down this repo to the godot api docs for ARVRServer. And the 3 methods mentioned were not on the method list of the API doc. I wasn't really sure where to go from there.

So are my assets versions just not compatible with each other and/or my Godot version?

**Comment by BastiaanOlij** [comment] 2018-08-06 22:08
Sounds like that all should work so I wonder what happened... I've been working on 3.1 for the past months, I'll make some time after work to test things at my end in 3.0.6 and see if we inadvertently broke something. At face value it sounds like you're doing the right thing.

**Comment by Pewsplosions** [comment] 2018-08-06 22:18
That would be very appreciated. I guess it could just be me. If so, we could just close this and I'll uninstall everything and try to start over from scratch. My environment could very well be the problem... it has been... finnicky as of late.

I am currently trying to set up a good VR demo with Godot to show my bosses at work, in an attempt to move the work away from Unity. Feels like adding in Leap controls would be a fun way to show off the potential.

**Comment by BastiaanOlij** [comment] 2018-08-07 11:59
Sounds like a nice project.

Well I'm breaking my head over this. The compile issue you had is simply because the master branch of GDNative is currently aligned with Godot 3.1 but its got an old godot-api.json file in there. We're close to merging nativescript-1.1 which uses the api.json stored in godot-headers so hasn't been updated yet. Putting the files in place manually allowed me to compile everything.

I've created a 3.0 branch linked to the 3.0 godot-cpp (which is awaiting merging a few fixes in 3.0.7 but seems to work otherwise).

Problem is, the moment I turn the leap motion on things freeze and I have no idea where it is getting stuck. I'll need to do a lot more experimenting to find out. Hopefully its just getting stuck in a loop somewhere. Unfortunately I don't have time to dive into that tonight. I might give it another look tomorrow but I might not get to it until the weekend.

**Comment by Pewsplosions** [comment] 2018-08-07 13:39
Ah no worries. I appreciate you at least checking it out. Gives me a bit of sanity to know it wasn't just me. I'll experiment more later today.

**Comment by BastiaanOlij** [comment] 2018-08-07 13:48
I found the cause of the problem, just committed a fix. I don't know why but for some reason the "wait_for_connection" method isn't yielding to the other thread. I don't know why that has changed as it used to work but alas.

I've changed the logic so instead of waiting it just toggles the flag but will run the needed command after it receives a connect signal if it wasn't already connected. 

I have to cherry pick this for the 3.0 branch and do a new 3.0 build but i have it working with 3.1. 3.1 developed a new issue that it's loosing the singleton status of the openvr driver though... that'll have to wait for another day, I'm off to bed :)

**Closed** 2020-04-25 11:30 UTC
